name: NodeJS Project Deployment

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: mkhizeryounas/express
        username: ${{ secrets.DOCKER_UESERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
#         registry: docker.io
#     - name: Run deployment with dropspot
#       run: |
#         npm i -g dropspot@latest
#         npx dropspot deploy -u $DROPSPOT_SERVER -t $DROPSPOT_DEPLOYMENT_TOKEN
      
      env:
        CI: true
        DROPSPOT_SERVER: ${{ secrets.DROPSPOT_SERVER }}
        DROPSPOT_DEPLOYMENT_TOKEN: ${{ secrets.DROPSPOT_DEPLOYMENT_TOKEN }}
